/**
 * Rappresenta gli id dei servizi offerti dall'ufficio pubblico
 */
public enum IdServizio {
    SRP,PB,RPC,OCP,CV
}
/*
SRP:SPEDIZIONE E RITIRO PACCHI ||SERVIZIO FISSO
PB: PAGAMENTO BOLLETTINI
RPC:RICARICA POSTEPAY E CELLULARI
OCP:OPERAZIONI SUL CONTO POSTALE ||SERVIZIO FISSO
CV:CAMBIO VALUTA
 */



