package servizio;
/*
non usata in V1.0
 */
public enum ServicesList {SRP,PB,RPC,OCP,CV
}
/*
SRP:SPEDIZIONE E RITIRO PACCHI
PB: PAGAMENTO BOLLETTINI
RPC:RICARICA POSTEPAY E CELLULARI
OCP:OPERAZIONI SUL CONTO POSTALE
CV:CAMBIO VALUTA
 */
